url: https://metacell.github.io
baseurl: /ModECIWebsite-Staging/

# Site settings
title: ModECI
email: your-email@domain.com
description: ModECI (Model Exchange and Convergence Initiative) is a multi-investigator collaboration that aims to develop a standardized format for exchanging computational models among neuroscience, cognitive science and machine learning.
githubLink: https://github.com/ModECI/Website
nsfLink: https://www.nsf.gov/od/oia/convergence-accelerator/

# Build settings
markdown: kramdown
permalink: pretty
